# Generated by Django 5.1.1 on 2024-10-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='qualifications',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expertise',
            field=models.TextField(help_text="Comma-separated list of candidate's areas of expertise"),
        ),
        migrations.AlterField(
            model_name='expert',
            name='expertise',
            field=models.TextField(help_text="Comma-separated list of expert's areas of expertise"),
        ),
    ]
